# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# added new workflow_dispatch trigger so you can run builds manually on any branch: 
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
  workflow_dispatch:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true

    # Cache
    - uses: actions/cache@v1.1.0
      with:
        path: Library
        key: Library

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Starting Unity

    - name: Unity - Builder
      uses: webbertakken/unity-builder@v0.12
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        # Version of unity to use for building the project.
        unityVersion: 2019.4.9f1
        # Platform that the build should target.
        targetPlatform: StandaloneWindows64  
        # Relative path to the project to be built.
        projectPath: ./
        buildName: SailingWithTheGods 

    - name: Unity - Builder
      uses: webbertakken/unity-builder@v0.12
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        # Version of unity to use for building the project.
        unityVersion: 2019.4.9f1
        # Platform that the build should target.
        targetPlatform: StandaloneOSX
        # Relative path to the project to be built.
        projectPath: ./
        buildName: SailingWithTheGods
    
    - name: Artifact Upload
      uses: actions/upload-artifact@v1
      with:
        name: Build
        path: build
        
    - name: File Existence
      uses: andstor/file-existence-action@v1.0.0
      with:
        # Comma separated string with paths to files and directories to check for existence.
        files: ./build/StandaloneWindows64/SailingWithTheGods.exe
        # Makes the Action fail on missing files.
        allow_failure: true
        
